NSE:
  INSTRUMENT: NIFTY
  EXPIRY: 23SEP
  LOT_SIZE: 50
  MAX_QTY: 1000
  PFOLIO_LAKHS: 1
  SEL_PREMIUM: 50
  BUY_PREMIUM: 10
  ENTRY_PERC: 20
  ENTRY_BEG_TIME: 09:15
  SQUARE_OFF_TIME: 15:20
  PFOLIO_SL_PERC: 1
  MAX_SOLD_LTP: 200
  DIFF_THRESHOLD: 0.7
  ADJUST_PERC: 3
  ADJUST_SEL_PREMIUM: 10
  ADJUST_BUY_PREMIUM: 50
  COVER_FOR_PROFIT: 10
MCX:
  STOP: -10000
  BUFF_PERC: 2
  IGNORE:
    - SILVERMIC30NOV23
